# site settings
title: Hamze Dokoohaki
subtitle: 
email: hamzed@bu.edu
description: Postdoctoral Associate @ Ecological Forecasting Lab
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 675 commonwealth avenue
city: Boston
state: MA
zip_code: '02215'
country: United States of America
phone: (515) 451-4178

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings
500px_url:
facebook_url:
github_url: https://github.com/para2x
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/hamzedokoo

# build settings
markdown: kramdown

sass:
  style: compressed

theme: jekyll-theme-cayman
